# Generated by Django 5.1.2 on 2024-11-01 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_survey_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='option_a',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_b',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_c',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_d',
        ),
    ]
